### ISSUE TITLE
Emojis do not appear in the chat

### ISSUE THREAD

**Issue by JuanmaAranda** [ZackyTalib/twidget#1]
Emojis are not displayed in the application window or in the chat. Instead it shows the name of the icon of the type :face_with_tongue:

I am using version 1.4.1-beta.

Greetings and thanks for the work!

**Comment by ZackyTalib** [comment]
Yeah, we'll probably be fixing that issue on the next update.

The problem is, these emojis aren't what we call "Unicode" emojis. So the emoji 🙄 for example is a Unicode emoji and it will display on Twidget. But youtube has emojis that are very specific to youtube and they're not technically emojis, they're actually rendered as images. And each channel can upload its own custom youtube emojis so this issue just gets quite complicated.

Ideally, though, we should add some code to the app that detects the ": :" symbols and then match it with a list of youtube emojis.
